accounts/urls.py
from django.urls import path, include
from accounts import views
from django.contrib import admin


app_name='accounts'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/',  views.login, name='login'),
    path('logout/', views.logout, name='logout'),
]

blog/urls.py
from django.urls import path
import blog.views
from django.contrib import admin

app_name='blog'

urlpatterns = [
    
    path('',blog.views.home, name='home'),
    path('new/',blog.views.new, name='new'),
    path('create/',blog.views.create, name='create'),
    path('portfolio/',blog.views.portfolio, name='portfolio'),
    path('newblog/',blog.views.blogpost, name='newblog'),
]

myproject/urls.py
from django.contrib import admin
from django.urls import path, include
import blog.views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',blog.views.home,name='home'),
    path('blog/',include('blog.urls', namespace='blog')),
    path('accounts/',include('accounts.urls', namespace='accounts')),
]

accounts/models.py
from django.db import models

# Create your models here.

blog/models.py
from django.db import models

# Create your models here.
class Blog(models.Model):
    objects=models.Manager()
    title =models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    body = models.TextField()

    
    def __str__(self):
        return self.title

blog/forms.py
from django import forms
from .models import Blog

class BlogPost(forms.ModelForm):
    class Meta:
        model = Blog
        fields = ['title', 'body']

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.contrib import auth

# Create your views here.
def signup(request):
    if request.method == 'POST':
        if request.POST['password1'] == request.POST['password2']:
            user = User.objects.create_user(
                request.POST['username'], password=request.POST['password1'])
            auth.login(request, user)
            return redirect('blog:home')
    return render(request, 'accounts/signup.html')

def login(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = auth.authenticate(request, username=username, password=password)
        if user is not None:
            auth.login(request, user)
            return redirect('blog:home')
        else:
            return render(request, 'login.html', {'error': 'username or password is incorrect.'})
    else:
        return render(request, 'accounts/login.html')

def logout(request):
    if request.method == 'POST':
        auth.logout(request)
        return redirect('home')
    return render(request, 'accounts/login.html')

blog/views.py
from django.shortcuts import render, redirect
from django.utils import timezone
from django.core.paginator import Paginator
from blog.models import Blog
from .forms import BlogPost

# Create your views here.

def home(request):
    blogs = Blog.objects
    blog_list = Blog.objects.all()
    paginator = Paginator(blog_list, 3)
    page = request.GET.get('page')
    posts = paginator.get_page(page)

    if 'search' in request.GET:
        query = request.GET['search']  
        blogs = Blog.objects.all().filter(title__contains=query)
        result = blogs    
        return render(request, 'home.html', {'searched_blogs' : result, 'query': query })    
    else:
        result = None
        return render(request, 'home.html', {'blogs': blogs, 'posts': posts})

    


def new(request):
    return render(request,'new.html')

def create(request):
    blog = Blog()
    blog.title = request.POST['title']
    blog.title = request.POST['body']
    blog.pub_date = timezone.datetime.now()
    blog.save()
    return redirect('/blog')

def portfolio(request):
    return render(request,'portfolio.html')

def blogpost(request):
    if request.method=='POST':
        form = BlogPost(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.pub_date=timezone.now()
            post.save()
            return redirect('/blog')
    else:
        form = BlogPost()
        return render(request, 'new.html',{'form':form})

accounts/templates/accounts/login.html
<h1>Login</h1>

<form method="POST" action="{% url 'accounts:login'%}">
  {% csrf_token %} Username:
  <br />
  <input name="username" type="text" value="" />
  <br />
  Password:
  <br />
  <input name="password" type="password" value="" />
  <br />
  <br />
  <input class="btn btn-primary" type="submit" value="Login" />
</form>

accounts/templates/accounts/signup.html
<h1>Sign Up!</h1>

<form method="POST" action="{% url 'accounts:signup'%}">
  {% csrf_token %} 
  Username:
  <br />
  <input name="username" type="text" value="" />
  <br />
  Password:
  <br />
  <input name="password1" type="password" value="" />
  <br />
  Confirm Password:
  <br />
  <input name="password2" type="password" value="" />
  <br />
  <br />
  <input class="btn btn-primary" type="submit" value="Sign Up!" />
</form>

blog/templates/home.html
{% extends 'base.html' %}

{% block content %}
<h1 style="margin-left:40%">나의 블로그 </h1><br>

<a href="{% url 'accounts:login' %}">로그인</a>
<a href="{% url 'accounts:signup' %}">회원가입</a>
<a href="{% url 'blog:newblog' %}">글쓰기</a><br>
<a href="{% url 'blog:portfolio' %}">포트폴리오</a>

<h1 style="margin-left:10%">글 검색하기</h1>
<br>
<p>
<section id="features">
	<div class="container">
	<div class=" col-12 col-12-medium">
<section>
	<form method="get" action=".">
		<div position="center" class="row  col-12 col-6-small aln-center margin-bottom-4" style="margin-left: auto">
			<input name="search" placeholder="글 제목 검색하기" type="text"  >
		<span><button type="submit" class="form-button-submit button icon fa-search  input_store" sty]le="">Search</button>
		</i></span>
		</div>
	</form>
</section>
</p>
<br>
<br>
{%if query %}
<p>Searched blogs for title : {{query}}</p>
{% if searched_blogs%}
{%for blogs in searched_blogs%}
{{blogs.title}}
{{blogs.pub_date}}
{{blogs.body}}
{% endfor %}
{% else %}
NO posts found.
{% endif %}
{% endif %}

{% if posts %}
<h1>전체글</h1>
{% for blog in posts %}
  <div class= "container">
     <h5>{{blog.title}}</h5>
     <h6>{{blog.pub_date}}</h6>
     <p class="card-text">{{blog.body}}</p>
    </div>
{% endfor %}
{% endif %}


{%if posts.has_previous%}
<a href="?page=1">First</a>
<a href="?page={{ posts.previous_page_number }}">Previous</a>
{%endif%}

<span>{{ posts.number }}</span>
<span>of</span>
<span>{{ posts.paginator.num_pages }}</span>

{%if posts.has_next%}
<a href="?page={{ posts.next_page_number }}">Next</a>
<a href="?page={{ posts.paginator.num_pages }}">Last</a>
{%endif%}

{% endblock %}

blog/templates/new.html
{% extends 'base.html' %}
{% block content %}
<a href="{%url 'blog:home' %}">홈으로</a><br>

<div class="container">
    <h1 style="color:orangered">글쓰기</h1>
    <form method="post" action="{% url 'blog:create' %}">
        {% csrf_token %}
        <table>
            {{form.as_table}}
        </table>
       
        <input class="btn btn-dark" type="submit" value="제출">
    </form>
</div>
{% endblock %}

blog/templates/portfolio.html
{% load staticfiles %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v3.8.5">
    <title>Album example · Bootstrap</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/4.3/examples/album/">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

    <!-- Bootstrap core CSS -->
<link href="/docs/4.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>
    <!-- Custom styles for this template -->
    <link href="album.css" rel="stylesheet">
  </head>
  <body>
    <header>
  <div class="collapse bg-dark" id="navbarHeader">
    <div class="container">
      <div class="row">
        <div class="col-sm-8 col-md-7 py-4">
          <h4 class="text-white">About</h4>
          <p class="text-muted">멋쟁이 사자처럼 7기 양수영</p>
        </div>
        <div class="col-sm-4 offset-md-1 py-4">
          <h4 class="text-white">Contact</h4>
          <ul class="list-unstyled">
            <li><a href="https://www.instagram.com/___suuuuo__o/" class="text-white">Follow on Instagram</a></li>
            <li><a href="https://www.facebook.com/profile.php?id=100015547321622" class="text-white">Be friend with me on FaceBook</a></li>
          </ul>
        </div>
      </div>
    </div>
  </div>
  <div class="navbar navbar-dark bg-dark shadow-sm">
    <div class="container d-flex justify-content-between">
      <a href="#" class="navbar-brand d-flex align-items-center">
        <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" aria-hidden="true" class="mr-2" viewBox="0 0 24 24" focusable="false"><path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z"/><circle cx="12" cy="13" r="4"/></svg>
        <strong>Portfolio</strong>
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    </div>
  </div>
</header>

<main role="main">


  <div class="album py-5 bg-light">
    <div class="container">

      <div class="row">
        <div class="col-md-4">
          <div class="card mb-4 shadow-sm">
           <img src="{% static 'a.jpg' %}",height=200>
            <div class="card-body">
              <p class="card-text">귀요미 건후 사진</p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <button type="button" class="btn btn-sm btn-outline-secondary">View</button>
                  <button type="button" class="btn btn-sm btn-outline-secondary">Edit</button>
                </div>
                <small class="text-muted">9 mins</small>
              </div>
            </div>
          </div>
        </div>
       
    </div>
  </div>

</main>

<footer class="text-muted">
  <div class="container">
    <p class="float-right">
      <a href="#">Back to top</a>
    </p>
  </div>
</footer>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
      <script>window.jQuery || document.write('<script src="/docs/4.3/assets/js/vendor/jquery-slim.min.js"><\/script>')</script><script src="/docs/4.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o" crossorigin="anonymous"></script></body>
</html>

myproject/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v3.8.5">
    
    <link rel="canonical" href="https://getbootstrap.com/docs/4.3/examples/album/">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

    <!-- Bootstrap core CSS -->
<link href="/docs/4.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>
    <!-- Custom styles for this template -->
    <link href="album.css" rel="stylesheet">
  </head>
  <body>
    <header>
  <div class="collapse bg-dark" id="navbarHeader">
    <div class="container">
      <div class="row">
        <div class="col-sm-8 col-md-7 py-4">
          <h4 class="text-white">About</h4>
          <p class="text-muted">멋쟁이 사자처럼 7기 양수영</p>
        </div>
        <div class="col-sm-4 offset-md-1 py-4">
          <h4 class="text-white">Contact</h4>
          <ul class="list-unstyled">
            <li><a href="https://www.instagram.com/___suuuuo__o/" class="text-white">Follow on Instagram</a></li>
            <li><a href="https://www.facebook.com/profile.php?id=100015547321622" class="text-white">Be friend with me on FaceBook</a></li>
          </ul>
        </div>
      </div>
    </div>
  </div>
  <div class="navbar navbar-dark bg-dark shadow-sm">
    <div class="container d-flex justify-content-between">
      <strong class="text-white">MY BLOG</strong>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    </div>
      </div>
</header>
    {% block content %}
    {% endblock %}

</html>